# Generated by Django 2.2.4 on 2020-06-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('age', models.TextField(blank=True, db_column='Age', null=True)),
                ('class_dept', models.TextField(blank=True, db_column='Class/Dept', null=True)),
                ('ticket', models.TextField(blank=True, db_column='Ticket', null=True)),
                ('joined', models.TextField(blank=True, db_column='Joined', null=True)),
                ('job', models.TextField(blank=True, db_column='Job', null=True)),
                ('boat_body_field', models.TextField(blank=True, db_column='Boat [Body]', null=True)),
            ],
            options={
                'db_table': 'Passenger_list',
                'managed': False,
            },
        ),
    ]
