# Generated by Django 2.2.4 on 2020-06-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicPassengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('class_dept', models.TextField(blank=True, db_column='Class/Dept', null=True)),
                ('cabin', models.TextField(blank=True, db_column='Cabin', null=True)),
                ('joined', models.TextField(blank=True, db_column='Joined', null=True)),
                ('occupation', models.TextField(blank=True, db_column='Occupation', null=True)),
                ('survived_field', models.TextField(blank=True, db_column='Survived?', null=True)),
                ('boat', models.TextField(blank=True, db_column='Boat', null=True)),
                ('body', models.TextField(blank=True, db_column='Body', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'titanic_passengers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PassengerList',
        ),
    ]
